# Generated by Django 5.2.7 on 2025-10-27 07:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('pro', 'Pro')], db_index=True, max_length=20, unique=True)),
                ('duration', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly (3 months)'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('daily_like_limit', models.IntegerField(default=10, help_text='Daily like limit (0 = unlimited)')),
                ('can_see_likes', models.BooleanField(default=False, help_text='Can see who liked them')),
                ('can_rewind', models.BooleanField(default=False, help_text='Can undo last swipe')),
                ('can_boost', models.BooleanField(default=False, help_text='Can boost profile')),
                ('can_super_like', models.BooleanField(default=False, help_text='Can send super likes')),
                ('super_likes_per_day', models.IntegerField(default=0, help_text='Daily super like limit')),
                ('male_chat_initiation', models.BooleanField(default=False, help_text='Males can initiate chats (Pro only)')),
                ('male_chat_limit', models.IntegerField(default=0, help_text='Max chats males can initiate (Pro: 25)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments_subscriptionplan',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('other', 'Other')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('external_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.subscriptionplan')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_trans_id', models.BigIntegerField(db_index=True, unique=True)),
                ('service_id', models.IntegerField()),
                ('merchant_trans_id', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('action', models.IntegerField(choices=[(0, 'Prepare'), (1, 'Complete')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('prepared', 'Prepared'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='pending', max_length=20)),
                ('error', models.IntegerField(default=0)),
                ('error_note', models.TextField(blank=True, null=True)),
                ('sign_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_transactions', to='payments.payment')),
            ],
            options={
                'db_table': 'payments_clicktransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme')], db_index=True, max_length=20)),
                ('request_method', models.CharField(max_length=10)),
                ('request_path', models.CharField(max_length=255)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('response_status', models.IntegerField()),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callbacks', to='payments.payment')),
            ],
            options={
                'db_table': 'payments_paymentcallback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_id', models.CharField(db_index=True, max_length=25, unique=True)),
                ('payme_time', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.IntegerField(choices=[(1, 'Created'), (2, 'Completed'), (-1, 'Cancelled (while waiting)'), (-2, 'Cancelled (after completion)')], db_index=True, default=1)),
                ('account', models.JSONField()),
                ('reason', models.IntegerField(blank=True, choices=[(1, 'Receiver not found'), (2, 'Processing error'), (3, 'Cancelled by timeout'), (4, 'Refund'), (5, 'Cancelled by user')], null=True)),
                ('cancel_time', models.BigIntegerField(blank=True, null=True)),
                ('create_time', models.BigIntegerField()),
                ('perform_time', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payme_transactions', to='payments.payment')),
            ],
            options={
                'db_table': 'payments_paymetransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending Payment')], db_index=True, default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_usersubscription',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='user_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.usersubscription'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='payments_us_user_id_7651b7_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['expires_at'], name='payments_us_expires_e1e2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_7a85fd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
    ]
