# Generated by Django 5.2.9 on 2026-04-24 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_clicktransaction_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('flash_boost', 'Flash Boost'), ('super_message', 'Super Message'), ('combo', 'Flash Boost + Super Message')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=13000)),
                ('boost_hours', models.PositiveIntegerField(default=0)),
                ('super_message_count', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_service',
            },
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='can_boost',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('service', 'Daily Service')], default='subscription', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_message_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_see_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='daily_skips',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_priority_in_discovery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.dailyservice'),
        ),
        migrations.CreateModel(
            name='UserDailyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_messages', models.SmallIntegerField(default=0)),
                ('boost_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.dailyservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_daily_service',
                'ordering': ['-created_at'],
            },
        ),
    ]
