# Generated by Django 5.2.9 on 2026-04-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_dailyservice_remove_subscriptionplan_can_boost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyservice',
            name='service_type',
        ),
        migrations.AlterField(
            model_name='dailyservice',
            name='boost_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='dailyservice',
            name='name',
            field=models.CharField(default='Kundalik paket', max_length=50),
        ),
        migrations.AlterField(
            model_name='dailyservice',
            name='super_message_count',
            field=models.SmallIntegerField(default=3),
        ),
    ]
