# Generated by Django 5.2.9 on 2026-04-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_service_type_from_dailyservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_months',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dailyservice',
            name='price',
            field=models.PositiveIntegerField(default=9900),
        ),
    ]
