# Generated by Django 5.2.9 on 2026-04-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_duration_days_to_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
