# Generated by Django 5.2.9 on 2026-04-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_add_unique_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyservice',
            name='plan_type',
            field=models.CharField(choices=[('daily', 'Daily')], default='daily', max_length=20),
        ),
    ]
