# Generated by Django 5.2.9 on 2026-04-30 06:04

from django.db import migrations


def rename_daily_to_boost(apps, schema_editor):
    DailyService = apps.get_model('payments', 'DailyService')
    DailyService.objects.filter(plan_type='daily').update(plan_type='boost')


def rename_boost_to_daily(apps, schema_editor):
    DailyService = apps.get_model('payments', 'DailyService')
    DailyService.objects.filter(plan_type='boost').update(plan_type='daily')


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_add_plan_type_to_dailyservice'),
    ]

    operations = [
        migrations.RunPython(rename_daily_to_boost, rename_boost_to_daily),
    ]
