# Generated by Django 5.2.9 on 2026-04-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_rename_daily_to_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyservice',
            name='plan_type',
            field=models.CharField(choices=[('boost', 'Boost')], default='boost', max_length=20),
        ),
    ]
