# Generated by Django 5.2.9 on 2026-05-02 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_usersubscription_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='platform',
            field=models.CharField(choices=[('mobile', 'Mobile App'), ('tg_app', 'Telegram App')], default='tg_app', max_length=10),
        ),
        migrations.AddField(
            model_name='userdailyservice',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_services', to='payments.payment'),
        ),
    ]
