# Generated by Django 5.2.9 on 2026-05-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_platform_userdailyservice_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='profile_views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
