# Generated by Django 5.2.9 on 2026-05-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_usersubscription_profile_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payme_create_time',
            field=models.PositiveIntegerField(blank=True, help_text='Payme transaction create time in ms', null=True),
        ),
    ]
