# Generated by Django 5.2.9 on 2026-05-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_payment_payme_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payme_create_time',
            field=models.BigIntegerField(blank=True, help_text='Payme transaction create time in ms', null=True),
        ),
    ]
