# Generated by Django 5.2.9 on 2026-05-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_payment_payme_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payme_cancel_time',
            field=models.BigIntegerField(blank=True, help_text='Payme transaction cancel time in ms', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payme_state',
            field=models.SmallIntegerField(blank=True, help_text='Payme transaction state: 1=created, 2=completed, -1=cancelled(pending), -2=cancelled(completed)', null=True),
        ),
    ]
