# Generated by Django 5.2.9 on 2026-05-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_payment_payme_cancel_time_payment_payme_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payme_cancel_reason',
            field=models.SmallIntegerField(blank=True, help_text='Payme cancel reason code', null=True),
        ),
    ]
