# Generated by Django 5.2.7 on 2025-10-23 11:37

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1)),
                ('date_of_birth', models.DateField(db_index=True)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users_customuser',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, choices=[('not_interested', 'Not Interested'), ('inappropriate', 'Inappropriate Behavior'), ('other', 'Other')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_block',
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('age_max', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('distance_km', models.IntegerField(default=50, help_text='Maximum distance for matches in km', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('education_min', models.CharField(choices=[('no_preference', 'No Preference'), ('high_school', 'High School'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD')], default='no_preference', max_length=20)),
                ('height_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)])),
                ('height_max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)])),
                ('marital_status_pref', models.JSONField(blank=True, default=list)),
                ('sect_pref', models.JSONField(blank=True, default=list)),
                ('prayer_frequency_min', models.CharField(choices=[('no_preference', 'No Preference'), ('sometimes', 'At least sometimes'), ('five_times', 'Five times daily')], default='no_preference', max_length=20)),
                ('ethnicity_pref', models.JSONField(blank=True, default=list)),
                ('languages_pref', models.JSONField(blank=True, default=list)),
                ('practice_level_pref', models.JSONField(blank=True, default=list)),
                ('wants_children_pref', models.BooleanField(blank=True, null=True)),
                ('willing_to_relocate_pref', models.BooleanField(blank=True, null=True)),
                ('show_me', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_preferences',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('height', models.IntegerField(blank=True, help_text='Height in cm', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)])),
                ('weight', models.IntegerField(blank=True, help_text='Weight in kg', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('education', models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], db_index=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('income_range', models.CharField(blank=True, choices=[('prefer_not_say', 'Prefer not to say'), ('under_50k', 'Under 50,000'), ('50k_100k', '50,000 - 100,000'), ('100k_200k', '100,000 - 200,000'), ('over_200k', 'Over 200,000')], max_length=20, null=True)),
                ('marital_status', models.CharField(choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], db_index=True, max_length=20)),
                ('has_children', models.BooleanField(default=False)),
                ('children_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('wants_children', models.BooleanField(default=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('profile_completion', models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('profile_views', models.IntegerField(default=0)),
                ('is_profile_public', models.BooleanField(db_index=True, default=True)),
                ('is_boosted', models.BooleanField(db_index=True, default=False)),
                ('boost_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_profile',
            },
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profiles/%Y/%m/')),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('is_blurred', models.BooleanField(default=False, help_text='For privacy mode')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_profilephoto',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReligiousProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sect', models.CharField(choices=[('sunni', 'Sunni'), ('shia', 'Shia'), ('other', 'Other'), ('prefer_not_say', 'Prefer not to say')], db_index=True, max_length=20)),
                ('madhab', models.CharField(blank=True, choices=[('hanafi', 'Hanafi'), ('maliki', 'Maliki'), ('shafi', 'Shafi'), ('hanbali', 'Hanbali'), ('jafari', 'Jafari'), ('other', 'Other')], db_index=True, max_length=30, null=True)),
                ('revert', models.BooleanField(default=False, help_text='Are you a revert/convert?')),
                ('prayer_frequency', models.CharField(choices=[('five_times', 'Five times daily'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely'), ('never', 'Never')], db_index=True, max_length=20)),
                ('quran_reading', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('rarely', 'Rarely'), ('never', 'Never')], db_index=True, max_length=20)),
                ('hijab_style', models.CharField(blank=True, choices=[('full_hijab', 'Full Hijab'), ('turban', 'Turban Style'), ('sometimes', 'Sometimes'), ('no', 'No')], db_index=True, max_length=30, null=True)),
                ('beard_status', models.CharField(blank=True, choices=[('full_beard', 'Full Beard'), ('trimmed', 'Trimmed'), ('clean_shaven', 'Clean Shaven')], db_index=True, max_length=20, null=True)),
                ('halal_meat_only', models.BooleanField(default=True)),
                ('attends_friday_prayer', models.BooleanField(default=False, help_text='For men')),
                ('islamic_education', models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('scholar', 'Scholar')], db_index=True, max_length=30)),
                ('practice_level', models.CharField(choices=[('very_practicing', 'Very Practicing'), ('moderate', 'Moderately Practicing'), ('cultural', 'Cultural Muslim')], db_index=True, max_length=20)),
                ('marriage_timeline', models.CharField(choices=[('asap', 'As soon as possible'), ('3_months', 'Within 3 months'), ('6_months', 'Within 6 months'), ('1_year', 'Within 1 year'), ('2_years', 'Within 2 years')], db_index=True, max_length=20)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('polygamy_acceptance', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=20, null=True)),
                ('requires_wali_approval', models.BooleanField(default=False)),
                ('wali_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wali_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('wali_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='religiousprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_religiousprofile',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['gender', 'is_active', 'is_verified'], name='users_custo_gender_d56a15_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['last_active'], name='users_custo_last_ac_714467_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocker', 'blocked'], name='users_block_blocker_3876ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('blocker', 'blocked')},
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['city', 'is_profile_public'], name='users_profi_city_6aa8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country', 'is_profile_public'], name='users_profi_country_88c3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='profilephoto',
            index=models.Index(fields=['user', 'is_primary'], name='users_profi_user_id_4dce46_idx'),
        ),
        migrations.AddIndex(
            model_name='profilephoto',
            index=models.Index(fields=['user', 'order'], name='users_profi_user_id_8848de_idx'),
        ),
    ]
