# Generated by Django 5.2.7 on 2025-10-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='drinking_pref',
            field=models.JSONField(blank=True, default=list, help_text='Acceptable drinking habits'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='marriage_type_pref',
            field=models.JSONField(blank=True, default=list, help_text='Preferred marriage types: religious, official, both'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='smoking_pref',
            field=models.JSONField(blank=True, default=list, help_text='Acceptable smoking habits'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='spouse_qualities_pref',
            field=models.JSONField(blank=True, default=list, help_text='Desired spouse qualities'),
        ),
        migrations.AddField(
            model_name='profile',
            name='disease',
            field=models.JSONField(blank=True, default=list, help_text='List of health conditions', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='drinking_alcohol',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('rarely', 'Rarely'), ('socially', 'Socially'), ('regularly', 'Regularly')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoking_cigarettes',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('regularly', 'Regularly')], db_index=True, max_length=20, null=True),
        ),
    ]
