# Generated by Django 5.2.7 on 2025-10-28 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_profileboost'),
        ('users', '0003_preferences_drinking_pref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_visibility', models.CharField(choices=[('public', 'Public - Everyone can see'), ('matches_only', 'Matches Only - Only matched users'), ('blurred', 'Blurred - Photos are blurred until matched'), ('private', 'Private - Nobody can see')], default='blurred', help_text='Who can see your photos', max_length=20)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public - Visible to all'), ('limited', 'Limited - Visible only to compatible matches'), ('private', 'Private - Hidden from discovery')], default='public', help_text='Who can see your full profile', max_length=20)),
                ('show_last_seen', models.CharField(choices=[('everyone', 'Everyone'), ('matches', 'Matches Only'), ('nobody', 'Nobody')], default='matches', help_text='Who can see when you were last active', max_length=20)),
                ('show_in_discovery', models.BooleanField(default=True, help_text='Show profile in discovery feed')),
                ('show_distance', models.BooleanField(default=True, help_text='Show your distance to other users')),
                ('send_read_receipts', models.BooleanField(default=True, help_text='Let others know when you read their messages')),
                ('show_online_status', models.BooleanField(default=True, help_text="Show when you're online")),
                ('allow_messages_from_non_matches', models.BooleanField(default=False, help_text="Allow messages from users you haven't matched with (Pro feature)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_privacy_settings',
            },
        ),
        migrations.CreateModel(
            name='WaliApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('wali_name', models.CharField(max_length=100)),
                ('wali_phone', models.CharField(max_length=20)),
                ('wali_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message_to_wali', models.TextField(blank=True, help_text='Message from the male user to the wali', null=True)),
                ('wali_response', models.TextField(blank=True, help_text='Response from wali', null=True)),
                ('verification_code', models.CharField(blank=True, help_text='Verification code sent to wali', max_length=6, null=True)),
                ('code_sent_at', models.DateTimeField(blank=True, null=True)),
                ('code_verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wali_approvals', to='matching.match')),
                ('match_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wali_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wali_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_wali_approval',
                'indexes': [models.Index(fields=['status', 'expires_at'], name='users_wali__status_c2a6da_idx'), models.Index(fields=['user', 'status'], name='users_wali__user_id_00ff3f_idx')],
                'unique_together': {('user', 'match_user')},
            },
        ),
    ]
