# Generated by Django 5.2.7 on 2025-10-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_privacysettings_waliapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_registration_complete',
            field=models.BooleanField(db_index=True, default=False, help_text='Has user completed basic registration (gender + DOB)?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1, null=True),
        ),
    ]
