# Generated by Django 5.2.7 on 2025-11-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_registration_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, db_index=True, help_text='District/Region within city', max_length=100, null=True),
        ),
    ]
