# Generated by Django 5.2.7 on 2025-11-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='religiousprofile',
            name='attended_to_haj',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('planning', 'Planning')], db_index=True, help_text='Have you performed Hajj?', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='religiousprofile',
            name='fasting',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('sometimes', 'Sometimes'), ('no', 'No')], db_index=True, help_text='Fasting frequency during Ramadan', max_length=20, null=True),
        ),
    ]
