# Generated by Django 5.2.7 on 2025-11-18 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_adminsupportchat_adminsupportmessage_and_more'),
        ('users', '0007_religiousprofile_attended_to_haj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_selfie', models.ImageField(help_text='Live selfie taken for verification', upload_to='verifications/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('manual_review', 'Manual Review')], db_index=True, default='pending', max_length=20)),
                ('face_match', models.BooleanField(default=False)),
                ('face_confidence', models.FloatField(default=0.0, help_text='Face match confidence (0-100)')),
                ('liveness_check_passed', models.BooleanField(default=False)),
                ('liveness_confidence', models.FloatField(default=0.0, help_text='Liveness confidence (0-100)')),
                ('verification_method', models.CharField(blank=True, choices=[('deepface', 'DeepFace (Local)'), ('aws_rekognition', 'AWS Rekognition'), ('manual', 'Manual Review')], max_length=20, null=True)),
                ('profile_quality_score', models.FloatField(default=0.0, help_text='Profile photo quality (0-100)')),
                ('selfie_quality_score', models.FloatField(default=0.0, help_text='Selfie quality (0-100)')),
                ('issues', models.JSONField(blank=True, default=list, help_text='List of issues found during verification')),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('attempt_number', models.IntegerField(default=1, help_text='Verification attempt count')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('profile_photo', models.ForeignKey(help_text='Profile photo used for verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='users.profilephoto')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to='admin_panel.adminuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_face_verification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='users_face__user_id_c851e3_idx'), models.Index(fields=['status', '-created_at'], name='users_face__status_bdd33c_idx')],
            },
        ),
    ]
