# Generated by Django 5.2.7 on 2025-11-20 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_faceverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
