# Generated by Django 5.2.7 on 2025-11-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_faceverification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='religiousprofile',
            name='attends_friday_prayer',
        ),
        migrations.RemoveField(
            model_name='religiousprofile',
            name='beard_status',
        ),
        migrations.RemoveField(
            model_name='religiousprofile',
            name='fasting',
        ),
        migrations.RemoveField(
            model_name='religiousprofile',
            name='halal_meat_only',
        ),
        migrations.RemoveField(
            model_name='religiousprofile',
            name='hijab_style',
        ),
        migrations.RemoveField(
            model_name='religiousprofile',
            name='islamic_education',
        ),
        migrations.RemoveField(
            model_name='religiousprofile',
            name='quran_reading',
        ),
        migrations.RemoveField(
            model_name='religiousprofile',
            name='requires_wali_approval',
        ),
        migrations.RemoveField(
            model_name='religiousprofile',
            name='wali_email',
        ),
        migrations.RemoveField(
            model_name='religiousprofile',
            name='wali_name',
        ),
        migrations.RemoveField(
            model_name='religiousprofile',
            name='wali_phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthplace_region',
            field=models.CharField(blank=True, help_text='Region where born', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='follow_daily_routine',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely')], db_index=True, help_text='Do you follow a daily routine?', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='follow_healthy_lifestyle',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('sometimes', 'Sometimes'), ('never', 'Never'), ('prefer_not_say', 'Prefer not to say')], db_index=True, help_text='Do you follow a healthy lifestyle?', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='relocate_for_partner',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('inside_country', 'Inside Country'), ('depending_on_situation', 'Depending on the Situation')], db_index=True, help_text='Would you relocate for your partner?', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='want_to_work_after_marriage',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('in_home', 'Work From Home'), ('depending_on_situation', 'Depending on the Situation')], db_index=True, help_text='Do you want to work after marriage?', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='where_willing_to_live',
            field=models.CharField(blank=True, choices=[('my_home', 'My Home'), ('wherever_my_husband_is', 'Wherever My Husband Is'), ('does_not_matter', 'Does Not Matter')], db_index=True, help_text='Where are you willing to live after marriage?', max_length=30, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='preferences',
                    name='willing_to_relocate_pref',
                    field=models.JSONField(blank=True, default=list, help_text='Preferred relocation options: yes, no, inside_country, depending_on_situation'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE users_preferences '
                        'ALTER COLUMN willing_to_relocate_pref DROP DEFAULT, '
                        "ALTER COLUMN willing_to_relocate_pref TYPE jsonb USING '[]'::jsonb, "
                        "ALTER COLUMN willing_to_relocate_pref SET DEFAULT '[]'::jsonb;"
                    ),
                    reverse_sql=(
                        'ALTER TABLE users_preferences '
                        'ALTER COLUMN willing_to_relocate_pref DROP DEFAULT, '
                        'ALTER COLUMN willing_to_relocate_pref TYPE boolean USING false, '
                        'ALTER COLUMN willing_to_relocate_pref SET DEFAULT false;'
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='religiousprofile',
            name='marriage_timeline',
            field=models.CharField(choices=[('not_sure', 'Not Sure'), ('between_1_or_2_years', 'Between 1 or 2 Years'), ('in_6_months', 'In 6 Months'), ('after_few_months', 'After Few Months'), ('family_makes_decisions', 'Family Makes Decisions')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='religiousprofile',
            name='willing_to_relocate',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('inside_country', 'Inside Country'), ('depending_on_situation', 'Depending on the Situation')], db_index=True, max_length=30, null=True),
        ),
    ]
