# Generated by Django 5.2.7 on 2025-11-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_religiousprofile_attends_friday_prayer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='face_verification_confidence',
            field=models.FloatField(default=0.0, help_text='Face match confidence (0-100)'),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='face_verification_date',
            field=models.DateTimeField(blank=True, help_text='When face verification was performed', null=True),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='face_verification_method',
            field=models.CharField(blank=True, help_text='deepface or aws_rekognition', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='face_verified',
            field=models.BooleanField(db_index=True, default=False, help_text="Verified against user's live selfie"),
        ),
    ]
