# Generated by Django 5.2.7 on 2025-11-27 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profilephoto_face_verification_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologicalAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1, null=True)),
                ('Q2', models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1, null=True)),
                ('Q3', models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1, null=True)),
                ('Q4', models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1, null=True)),
                ('Q5', models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1, null=True)),
                ('Q6', models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1, null=True)),
                ('Q7', models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1, null=True)),
                ('ES', models.FloatField(default=0)),
                ('AG', models.FloatField(default=0)),
                ('EX', models.FloatField(default=0)),
                ('CO', models.FloatField(default=0)),
                ('IN', models.FloatField(default=0)),
                ('CL', models.FloatField(default=0)),
                ('introvert_extrovert_score', models.CharField(blank=True, choices=[('E', 'Extrovert'), ('I', 'Introvert')], max_length=1, null=True)),
                ('judging_perceiving_score', models.CharField(blank=True, choices=[('J', 'Judging'), ('P', 'Perceiving')], max_length=1, null=True)),
                ('sensing_intuition_score', models.CharField(blank=True, choices=[('S', 'Sensing'), ('N', 'Intuition')], max_length=1, null=True)),
                ('thinking_feeling_score', models.CharField(blank=True, choices=[('T', 'Thinking'), ('F', 'Feeling')], max_length=1, null=True)),
                ('archetype', models.CharField(blank=True, choices=[('peace_seeker', 'Peace Seeker'), ('planner', 'Planner'), ('social_extrovert', 'Social Extrovert'), ('analytical_introvert', 'Analytical Introvert'), ('active_adventurer', 'Active Adventurer')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychological_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_psychological_answers',
                'indexes': [models.Index(fields=['archetype'], name='users_psych_archety_a34a1f_idx'), models.Index(fields=['introvert_extrovert_score', 'judging_perceiving_score', 'sensing_intuition_score', 'thinking_feeling_score'], name='users_psych_introve_95786d_idx')],
            },
        ),
    ]
