# Generated by Django 5.2.7 on 2025-11-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_psychologicalanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='religiousprofile',
            name='religious_identity',
            field=models.CharField(choices=[('islam', 'Islam'), ('christianity', 'Christianity'), ('Athiesm', 'Atheism'), ('other', 'Other'), ('prefer_not_say', 'Prefer not to say')], db_index=True, default='islam', help_text='Your religious identity', max_length=30),
        ),
    ]
