# Generated by Django 5.2.7 on 2025-11-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_religiousprofile_religious_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='dressing_style_pref',
            field=models.JSONField(blank=True, default=list, help_text='Preferred dressing styles: modern, simple, sportswear, classic, traditional, mixed, hijab'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dressing_style',
            field=models.CharField(blank=True, choices=[('modern', 'Modern'), ('simple', 'Simple'), ('sportswear', 'Sportswear'), ('classic', 'Classic'), ('traditional', 'Traditional'), ('mixed', 'Mixed'), ('hijab', 'Hijab')], db_index=True, help_text='Preferred dressing style', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_books',
            field=models.JSONField(blank=True, default=list, help_text='List of favorite books'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_musics',
            field=models.JSONField(blank=True, default=list, help_text='List of favorite music genres/artists'),
        ),
        migrations.AddField(
            model_name='profile',
            name='visited_countries',
            field=models.JSONField(blank=True, default=list, help_text='List of countries visited'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='List of interests'),
        ),
    ]
