# Generated by Django 5.2.7 on 2025-11-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_preferences_dressing_style_pref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='drinking_alcohol',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('try_to_quit', 'Try to Quit'), ('socially', 'Socially'), ('regularly', 'Regularly')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='smoking_cigarettes',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('try_to_quit', 'Try to Quit'), ('regularly', 'Regularly')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wants_children',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
