# Generated by Django 5.2.7 on 2025-11-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_drinking_alcohol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('devorced_with_children', 'Divorced with Children'), ('widowed_with_children', 'Widowed with Children'), ('divorced_without_children', 'Divorced without Children'), ('widowed_without_children', 'Widowed without Children'), ('married', 'Married')], db_index=True, max_length=50),
        ),
    ]
