# Generated by Django 5.2.7 on 2025-12-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilephoto',
            name='is_blurred',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_blurred',
            field=models.BooleanField(db_index=True, default=False, help_text='Blur all profile photos for privacy (only unblurred for owner)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dressing_style',
            field=models.CharField(blank=True, choices=[('modern', 'Modern'), ('simple', 'Simple'), ('sportswear', 'Sportswear'), ('classic', 'Classic'), ('traditional', 'Traditional'), ('mixed', 'Mixed'), ('hijab', 'Hijab'), ('official', 'Official'), ('daily', 'Daily')], db_index=True, help_text='Preferred dressing style', max_length=20, null=True),
        ),
    ]
