# Generated by Django 5.2.9 on 2026-02-03 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_profilephoto_is_blurred_profile_is_blurred_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_telegram_id', models.BigIntegerField(db_index=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_parent_connection',
            },
        ),
    ]
