# Generated by Django 5.2.9 on 2026-02-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_preferences_age_max_alter_preferences_age_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='show_me',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women')], db_index=True, max_length=10, null=True),
        ),
    ]
