# Generated by Django 5.2.9 on 2026-02-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_customuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('devorced_with_children', 'Divorced with Children'), ('widowed_with_children', 'Widowed with Children'), ('divorced_without_children', 'Divorced without Children'), ('widowed_without_children', 'Widowed without Children'), ('married', 'Married')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wants_children',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='religiousprofile',
            name='attended_to_haj',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('planning', 'Planning')], help_text='Have you performed Hajj?', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='religiousprofile',
            name='madhab',
            field=models.CharField(blank=True, choices=[('hanafi', 'Hanafi'), ('maliki', 'Maliki'), ('shafi', 'Shafi'), ('hanbali', 'Hanbali'), ('jafari', 'Jafari'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='religiousprofile',
            name='marriage_timeline',
            field=models.CharField(blank=True, choices=[('not_sure', 'Not Sure'), ('between_1_or_2_years', 'Between 1 or 2 Years'), ('in_6_months', 'In 6 Months'), ('after_few_months', 'After Few Months'), ('family_makes_decisions', 'Family Makes Decisions')], db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='religiousprofile',
            name='practice_level',
            field=models.CharField(blank=True, choices=[('very_practicing', 'Very Practicing'), ('moderate', 'Moderately Practicing'), ('cultural', 'Cultural Muslim')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='religiousprofile',
            name='prayer_frequency',
            field=models.CharField(blank=True, choices=[('five_times', 'Five times daily'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely'), ('never', 'Never')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='religiousprofile',
            name='sect',
            field=models.CharField(blank=True, choices=[('sunni', 'Sunni'), ('shia', 'Shia'), ('other', 'Other'), ('prefer_not_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='religiousprofile',
            name='willing_to_relocate',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('inside_country', 'Inside Country'), ('depending_on_situation', 'Depending on the Situation')], max_length=30, null=True),
        ),
    ]
