# Generated by Django 5.2.9 on 2026-03-07 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_profile_city_alter_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='drinking_preference',
            field=models.CharField(blank=True, help_text='Single drinking preference', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='education_min_plural',
            field=models.JSONField(blank=True, default=list, help_text='Preferred education levels'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='follow_daily_routine_pref',
            field=models.CharField(blank=True, help_text='Daily routine preference', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='occupation_pref',
            field=models.JSONField(blank=True, default=list, help_text='Preferred occupations'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='religious_identity_pref',
            field=models.CharField(blank=True, help_text='Preferred religious identity', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='smoking_preference',
            field=models.CharField(blank=True, help_text='Single smoking preference', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='weight_max',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='preferences',
            name='weight_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='education_min',
            field=models.CharField(blank=True, choices=[('no_preference', 'No Preference'), ('high_school', 'High School'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD')], max_length=20, null=True),
        ),
    ]
