# Generated by Django 5.2.9 on 2026-03-11 16:12

import django.core.validators
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_preferences_drinking_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceverification',
            name='live_selfie',
            field=models.ImageField(help_text='Live selfie taken for verification', upload_to='verifications/%Y/%m/', validators=[utils.validators.validate_file_size, utils.validators.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='height_max',
            field=models.IntegerField(default=250, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='height_min',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='weight_max',
            field=models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='weight_min',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='image',
            field=models.ImageField(upload_to='profiles/%Y/%m/', validators=[utils.validators.validate_file_size, utils.validators.validate_image_type]),
        ),
    ]
