# Generated by Django 5.2.9 on 2026-03-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_faceverification_live_selfie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='source_platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('other', 'Other')], db_index=True, default='other', help_text='Platform where user came from (Instagram, Telegram, etc.)', max_length=20),
        ),
    ]
