# Generated by Django 5.2.9 on 2026-04-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_customuser_source_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
