# Generated by Django 5.2.9 on 2026-04-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_securityquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='platform',
            field=models.CharField(choices=[('tg_app', 'Telegram Mini App'), ('mobile', 'Mobile App'), ('other', 'Other')], db_index=True, default='tg_app', help_text='App platform: tg_app (Telegram Mini App) or mobile (Mobile App)', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='source_platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], db_index=True, default='other', help_text='Platform where user came from (Instagram, Telegram, etc.)', max_length=20),
        ),
    ]
