# Generated by Django 5.2.9 on 2026-04-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_customuser_platform_alter_customuser_source_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='children_preference',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('depends', 'Depends on situation'), ('will_tell', 'Will tell spouse')], db_index=True, help_text='Preference about having children', max_length=10, null=True),
        ),
    ]
