# Generated by Django 5.2.9 on 2026-04-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_add_children_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='children_preference_pref',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('depends', 'Depends on situation'), ('will_tell', 'Will tell spouse')], help_text="Preferred partner's children preference", max_length=10, null=True),
        ),
    ]
