# Generated by Django 5.2.9 on 2026-04-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_add_children_preference_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=28, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=28, null=True),
        ),
    ]
