# Generated by Django 5.2.9 on 2026-04-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_profile_latitude_alter_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='birthplace_region_pref',
            field=models.CharField(blank=True, help_text='Filter by birthplace region', max_length=60, null=True),
        ),
    ]
