# Generated by Django 5.2.9 on 2026-04-24 05:01

from django.db import migrations, models


def fix_occupation_values(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')

    Profile.objects.filter(occupation='employed').update(occupation='employee')
    Profile.objects.filter(occupation='entrepreneur').update(occupation='businessman')
    Profile.objects.filter(occupation='to_candidate').update(occupation='prefer_not')


def reverse_occupation_values(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_add_birthplace_region_pref'),
    ]

    operations = [
        migrations.RunPython(fix_occupation_values, reverse_occupation_values),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee'), ('businessman', 'Businessman'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('prefer_not', 'Prefer not to say'), ('housewife', 'Housewife')], db_index=True, max_length=20, null=True),
        ),
    ]
