# Generated by Django 5.2.9 on 2026-04-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_add_occupation_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dressing_style',
            field=models.CharField(blank=True, choices=[('modern', 'Modern'), ('simple', 'Simple'), ('sportswear', 'Sportswear'), ('classic', 'Classic'), ('traditional', 'Traditional'), ('mixed', 'Mixed'), ('hijab', 'Hijab'), ('official', 'Official'), ('daily', 'Daily'), ('depends_on_situation', 'Depends on situation')], db_index=True, help_text='Preferred dressing style', max_length=20, null=True),
        ),
    ]
