# Generated by Django 5.2.9 on 2026-05-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_add_depends_on_situation_dressing_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='core_values',
            field=models.JSONField(blank=True, default=list, help_text="User's core values (max 3): family, faith, respect, stability, freedom, career, kindness"),
        ),
        migrations.AddField(
            model_name='profile',
            name='dealbreakers',
            field=models.JSONField(blank=True, default=list, help_text="User's dealbreakers: smoking, drinking, not_serious, no_children"),
        ),
        migrations.AddField(
            model_name='profile',
            name='personality_type',
            field=models.CharField(blank=True, choices=[('calm_thinker', 'Calm Thinker'), ('emotional', 'Emotional'), ('adaptive', 'Adaptive')], help_text="User's personality type: calm_thinker, emotional, adaptive", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_goal',
            field=models.CharField(blank=True, choices=[('serious', 'Serious Relationship'), ('casual', 'Casual Dating'), ('not_sure', 'Not Sure Yet')], help_text='What user is looking for: serious, casual, not_sure', max_length=20, null=True),
        ),
    ]
