# Generated by Django 5.2.9 on 2026-05-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_add_ai_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_portrait',
            field=models.TextField(blank=True, help_text='AI generated personality description', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list, help_text='AI generated tags'),
        ),
    ]
