# Generated by Django 5.2.9 on 2026-05-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_add_ai_portrait_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ideal_partner_qualities',
            field=models.JSONField(blank=True, default=list, help_text='Ideal partner qualities for AI matching (max 5)'),
        ),
    ]
