# Generated by Django 5.2.9 on 2026-05-24 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_add_ideal_partner_qualities'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='churn_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='churn_risk',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=8),
        ),
        migrations.AddField(
            model_name='customuser',
            name='churn_score',
            field=models.FloatField(default=0, help_text='Churn probability 0-1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referrer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trust_score',
            field=models.IntegerField(db_index=True, default=0, help_text='Trust score 0-100'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trust_score_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='utm_campaign',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='utm_medium',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
