# Generated by Django 5.2.9 on 2026-05-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_add_crm_metrics_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentconnection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='parentconnection',
            name='invite_token',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parentconnection',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentconnection',
            name='parent_telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
