# Generated by Django 5.2.9 on 2026-06-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_waliapproval_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacysettings',
            name='photo_visibility',
            field=models.CharField(choices=[('public', 'Public - Everyone can see'), ('contacts_only', 'Contacts Only - Only users with chat'), ('private', 'Private - Nobody can see')], default='public', help_text='Who can see your photos', max_length=20),
        ),
    ]
