# Generated by Django 5.2.9 on 2026-06-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_change_photo_visibility_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='reason',
            field=models.CharField(blank=True, choices=[('not_interested', 'Not Interested'), ('married', 'Married Person'), ('fake_profile', 'Fake Profile'), ('violence', 'Violence or Threats'), ('underage', 'Underage User'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
