# Generated by Django 5.2.9 on 2026-06-09 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_update_report_block_reasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_goal', models.CharField(blank=True, choices=[('serious', 'Serious Relationship'), ('casual', 'Casual Dating'), ('not_sure', 'Not Sure Yet')], max_length=20, null=True)),
                ('core_values', models.JSONField(blank=True, default=list)),
                ('dealbreakers', models.JSONField(blank=True, default=list)),
                ('personality_type', models.CharField(blank=True, choices=[('calm_thinker', 'Calm Thinker'), ('emotional', 'Emotional'), ('adaptive', 'Adaptive')], max_length=20, null=True)),
                ('ideal_partner_qualities', models.JSONField(blank=True, default=list)),
                ('portrait_text', models.TextField(blank=True, null=True)),
                ('portrait_tags', models.JSONField(blank=True, default=list)),
                ('portrait_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_ai_profile',
            },
        ),
    ]
