# Generated by Django 5.2.9 on 2026-06-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_create_ai_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiprofile',
            name='portrait_tags',
        ),
    ]
