# Generated by Django 5.2.9 on 2026-06-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_remove_portrait_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprofile',
            name='portrait_tags',
            field=models.JSONField(blank=True, default=list, help_text='AI generated tags: [{emoji, label, description}, ...]'),
        ),
    ]
