# Generated by Django 5.2.9 on 2026-06-20 06:03

from django.db import migrations, models

from users.models import generate_public_id


def fill_public_ids(apps, schema_editor):
    """Mavjud userlarga takrorlanmas public_id tarqatadi."""
    User = apps.get_model('users', 'CustomUser')
    used = set(
        User.objects.exclude(public_id__isnull=True).values_list('public_id', flat=True)
    )
    to_update = []
    for user in User.objects.filter(public_id__isnull=True).only('id').iterator():
        for _ in range(10):
            code = generate_public_id()
            if code not in used:
                used.add(code)
                user.public_id = code
                to_update.append(user)
                break
    User.objects.bulk_update(to_update, ['public_id'], batch_size=500)


def reverse_noop(apps, schema_editor):
    # Orqaga qaytarishda public_id'larni tozalashga hojat yo'q.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_add_portrait_tags_to_aiprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text="Admin panelda qidirish uchun takrorlanmas, o'qishga oson kod (masalan: K7M3PQ)", max_length=12, null=True, unique=True),
        ),
        migrations.RunPython(fill_public_ids, reverse_noop),
    ]