# Generated by Django 5.2.9 on 2026-06-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_customuser_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deletion_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deletion_reason',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the user requested account deletion. Hard-deleted 30 days later.', null=True),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='blurred_image',
            field=models.ImageField(blank=True, help_text='Pre-blurred copy served when photo_visibility is private/contacts_only', null=True, upload_to='profiles/blurred/%Y/%m/'),
        ),
    ]
