# Generated by Django 5.2.9 on 2026-06-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_customuser_deletion_note_customuser_deletion_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='churn_risk',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='churn_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referrer_user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='trust_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='utm_campaign',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='utm_medium',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_registration_complete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
