# Generated by Django 5.2.9 on 2026-06-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_remove_customuser_churn_risk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ai_portrait',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ai_tags',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='core_values',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dealbreakers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ideal_partner_qualities',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_blurred',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='personality_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='relationship_goal',
        ),
    ]
