# Generated by Django 5.2.9 on 2026-07-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_remove_profile_ai_portrait_remove_profile_ai_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='religiousprofile',
            name='practice_level',
        ),
    ]
