# Generated by Django 5.2.9 on 2026-07-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_remove_religiousprofile_practice_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacysettings',
            name='allow_messages_from_non_matches',
        ),
        migrations.RemoveField(
            model_name='privacysettings',
            name='profile_visibility',
        ),
        migrations.RemoveField(
            model_name='privacysettings',
            name='send_read_receipts',
        ),
        migrations.RemoveField(
            model_name='privacysettings',
            name='show_distance',
        ),
        migrations.RemoveField(
            model_name='privacysettings',
            name='show_last_seen',
        ),
        migrations.RemoveField(
            model_name='privacysettings',
            name='show_online_status',
        ),
    ]
