# Generated by Django 5.2.9 on 2026-07-03 18:42

import django.core.validators
import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_remove_privacysettings_allow_messages_from_non_matches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceverification',
            name='attempt_number',
        ),
        migrations.RemoveField(
            model_name='faceverification',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='faceverification',
            name='liveness_check_passed',
        ),
        migrations.RemoveField(
            model_name='faceverification',
            name='liveness_confidence',
        ),
        migrations.RemoveField(
            model_name='faceverification',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='profilephoto',
            name='face_verification_confidence',
        ),
        migrations.RemoveField(
            model_name='profilephoto',
            name='face_verification_date',
        ),
        migrations.RemoveField(
            model_name='profilephoto',
            name='face_verification_method',
        ),
        migrations.RemoveField(
            model_name='profilephoto',
            name='face_verified',
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='core_values',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='dealbreakers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='ideal_partner_qualities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='personality_type',
            field=models.CharField(choices=[('calm_thinker', 'Calm Thinker'), ('emotional', 'Emotional'), ('adaptive', 'Adaptive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='portrait_generated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='portrait_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='portrait_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='relationship_goal',
            field=models.CharField(choices=[('serious', 'Serious Relationship'), ('casual', 'Casual Dating'), ('not_sure', 'Not Sure Yet')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='reason',
            field=models.CharField(choices=[('not_interested', 'Not Interested'), ('married', 'Married Person'), ('fake_profile', 'Fake Profile'), ('violence', 'Violence or Threats'), ('underage', 'Underage User'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='deletion_note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='deletion_reason',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='deletion_requested_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='platform',
            field=models.CharField(choices=[('tg_app', 'Telegram Mini App'), ('mobile', 'Mobile App'), ('other', 'Other')], db_index=True, default='tg_app', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='source_platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], db_index=True, default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='face_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='live_selfie',
            field=models.ImageField(upload_to='verifications/%Y/%m/', validators=[utils.validators.validate_file_size, utils.validators.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='profile_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='users.profilephoto'),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='rejection_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='verification_method',
            field=models.CharField(choices=[('deepface', 'DeepFace (Local)'), ('aws_rekognition', 'AWS Rekognition'), ('manual', 'Manual Review')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parentconnection',
            name='connected_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='parentconnection',
            name='invite_token',
            field=models.CharField(db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parentconnection',
            name='parent_telegram_id',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='age_max',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='age_min',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='birthplace_region_pref',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='children_preference_pref',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('depends', 'Depends on situation'), ('will_tell', 'Will tell spouse')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='drinking_preference',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='education_min_plural',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='follow_daily_routine_pref',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='marital_status_pref',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='occupation_pref',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='religious_identity_pref',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='show_me',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='smoking_preference',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='spouse_qualities_pref',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='photo_visibility',
            field=models.CharField(choices=[('public', 'Public - Everyone can see'), ('contacts_only', 'Contacts Only - Only users with chat'), ('private', 'Private - Nobody can see')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='show_in_discovery',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthplace_region',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='children_preference',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('depends', 'Depends on situation'), ('will_tell', 'Will tell spouse')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dressing_style',
            field=models.CharField(choices=[('modern', 'Modern'), ('simple', 'Simple'), ('sportswear', 'Sportswear'), ('classic', 'Classic'), ('traditional', 'Traditional'), ('mixed', 'Mixed'), ('hijab', 'Hijab'), ('official', 'Official'), ('daily', 'Daily'), ('depends_on_situation', 'Depends on situation')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='drinking_alcohol',
            field=models.CharField(choices=[('never', 'Never'), ('try_to_quit', 'Try to Quit'), ('socially', 'Socially'), ('regularly', 'Regularly')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('high_school', 'High School'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourite_books',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourite_musics',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='follow_daily_routine',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='follow_healthy_lifestyle',
            field=models.CharField(choices=[('always', 'Always'), ('sometimes', 'Sometimes'), ('never', 'Never'), ('prefer_not_say', 'Prefer not to say')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(decimal_places=25, max_digits=28, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=25, max_digits=28, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('devorced_with_children', 'Divorced with Children'), ('widowed_with_children', 'Widowed with Children'), ('divorced_without_children', 'Divorced without Children'), ('widowed_without_children', 'Widowed without Children'), ('married', 'Married')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('businessman', 'Businessman'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('prefer_not', 'Prefer not to say'), ('housewife', 'Housewife')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='smoking_cigarettes',
            field=models.CharField(choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('try_to_quit', 'Try to Quit'), ('regularly', 'Regularly')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visited_countries',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='blurred_image',
            field=models.ImageField(null=True, upload_to='profiles/blurred/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='rejection_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='psychologicalanswers',
            name='Q1',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='psychologicalanswers',
            name='Q2',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='psychologicalanswers',
            name='Q3',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='psychologicalanswers',
            name='Q4',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='psychologicalanswers',
            name='Q5',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='psychologicalanswers',
            name='Q6',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='psychologicalanswers',
            name='Q7',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='psychologicalanswers',
            name='archetype',
            field=models.CharField(choices=[('peace_seeker', 'Peace Seeker'), ('planner', 'Planner'), ('social_extrovert', 'Social Extrovert'), ('analytical_introvert', 'Analytical Introvert'), ('active_adventurer', 'Active Adventurer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='psychologicalanswers',
            name='introvert_extrovert_score',
            field=models.CharField(choices=[('E', 'Extrovert'), ('I', 'Introvert')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='psychologicalanswers',
            name='judging_perceiving_score',
            field=models.CharField(choices=[('J', 'Judging'), ('P', 'Perceiving')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='psychologicalanswers',
            name='sensing_intuition_score',
            field=models.CharField(choices=[('S', 'Sensing'), ('N', 'Intuition')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='psychologicalanswers',
            name='thinking_feeling_score',
            field=models.CharField(choices=[('T', 'Thinking'), ('F', 'Feeling')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='religiousprofile',
            name='marriage_timeline',
            field=models.CharField(choices=[('not_sure', 'Not Sure'), ('between_1_or_2_years', 'Between 1 or 2 Years'), ('in_6_months', 'In 6 Months'), ('after_few_months', 'After Few Months'), ('family_makes_decisions', 'Family Makes Decisions')], db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='religiousprofile',
            name='religious_identity',
            field=models.CharField(choices=[('islam', 'Islam'), ('christianity', 'Christianity'), ('Athiesm', 'Atheism'), ('other', 'Other'), ('prefer_not_say', 'Prefer not to say')], db_index=True, default='islam', max_length=30),
        ),
    ]
