# Generated by Django 5.2.9 on 2026-07-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_remove_faceverification_attempt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marriage_timeline',
            field=models.CharField(choices=[('not_sure', 'Not Sure'), ('between_1_or_2_years', 'Between 1 or 2 Years'), ('in_6_months', 'In 6 Months'), ('after_few_months', 'After Few Months'), ('family_makes_decisions', 'Family Makes Decisions')], db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='religious_identity',
            field=models.CharField(choices=[('islam', 'Islam'), ('christianity', 'Christianity'), ('Athiesm', 'Atheism'), ('other', 'Other'), ('prefer_not_say', 'Prefer not to say')], db_index=True, max_length=30, null=True),
        ),
    ]
