# Generated by Django 5.2.9 on 2026-07-08 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_profile_qualities'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='found_match_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_as_match_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
