# Generated by Django 5.2.9 on 2026-07-14 04:33

from django.db import migrations, models


def backfill_auth_method(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.filter(
        platform='tg_app', auth_method__isnull=True
    ).update(auth_method='telegram')
    CustomUser.objects.filter(
        platform='mobile', auth_method__isnull=True
    ).update(auth_method='phone')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_customuser_found_match_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_method',
            field=models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('phone', 'Phone'), ('google', 'Google'), ('email', 'Email')], db_index=True, max_length=20, null=True),
        ),
        migrations.RunPython(backfill_auth_method, migrations.RunPython.noop),
    ]
