# Generated by Django 5.2.9 on 2026-07-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_customuser_auth_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_first_name',
        ),
    ]
