# Generated by Django 5.2.9 on 2026-07-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_remove_customuser_telegram_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='spouse_qualities_pref',
        ),
    ]
