# Generated by Django 5.2.9 on 2026-07-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_remove_preferences_spouse_qualities_pref'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReligiousProfile',
        ),
    ]
