# Generated by Django 5.2.9 on 2026-07-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_regenerate_public_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('user', 'User'), ('guardian', 'Guardian')], db_index=True, default='user', max_length=10),
        ),
    ]
