# Generated by Django 5.2.9 on 2026-07-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_customuser_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
    ]
