# Generated by Django 5.2.9 on 2026-08-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_remove_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_method',
            field=models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('auth_with_telegram', 'Auth with Telegram'), ('telegram_to_mobile', 'Telegram to Mobile'), ('phone', 'Phone'), ('google', 'Google'), ('email', 'Email')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='platform',
            field=models.CharField(choices=[('tg_app', 'Telegram Mini App'), ('mobile', 'Mobile App')], db_index=True, default='tg_app', max_length=10),
        ),
    ]
