# Generated by Django 5.2.9 on 2026-08-03 06:28

import django.core.validators
from django.db import migrations, models


def copy_security_answers(apps, schema_editor):
    SecurityQuestion = apps.get_model('users', 'SecurityQuestion')
    Profile = apps.get_model('users', 'Profile')
    for sq in SecurityQuestion.objects.all().iterator():
        Profile.objects.filter(user_id=sq.user_id).update(
            security_answer_hash=sq.answer_hash,
            security_answer_updated_at=sq.updated_at,
        )


def restore_security_answers(apps, schema_editor):
    SecurityQuestion = apps.get_model('users', 'SecurityQuestion')
    Profile = apps.get_model('users', 'Profile')
    for p in Profile.objects.exclude(security_answer_hash=None).iterator():
        SecurityQuestion.objects.update_or_create(
            user_id=p.user_id,
            defaults={'answer_hash': p.security_answer_hash},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_alter_customuser_auth_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='security_answer_hash',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_answer_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_method',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('auth_with_telegram', 'Auth with Telegram'), ('telegram_to_mobile', 'Telegram to Mobile'), ('phone', 'Phone'), ('google', 'Google'), ('email', 'Email')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('manual_review', 'Manual Review')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='show_me',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthplace_region',
            field=models.CharField(db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dressing_style',
            field=models.CharField(choices=[('modern', 'Modern'), ('simple', 'Simple'), ('sportswear', 'Sportswear'), ('classic', 'Classic'), ('traditional', 'Traditional'), ('mixed', 'Mixed'), ('hijab', 'Hijab'), ('official', 'Official'), ('daily', 'Daily'), ('depends_on_situation', 'Depends on situation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='follow_healthy_lifestyle',
            field=models.CharField(choices=[('always', 'Always'), ('sometimes', 'Sometimes'), ('never', 'Never'), ('prefer_not_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(db_index=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marriage_timeline',
            field=models.CharField(choices=[('not_sure', 'Not Sure'), ('between_1_or_2_years', 'Between 1 or 2 Years'), ('in_6_months', 'In 6 Months'), ('after_few_months', 'After Few Months'), ('family_makes_decisions', 'Family Makes Decisions')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_completion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(db_index=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(copy_security_answers, restore_security_answers),
        migrations.DeleteModel(
            name='SecurityQuestion',
        ),
    ]
