# Generated by Django 5.2.9 on 2026-08-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_profile_security_answer_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
