# Generated by Django 5.2.9 on 2026-08-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_remove_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilephoto',
            name='rejection_reason',
        ),
    ]
