from django.urls import path

from .auth import (
    AdminLoginView, AdminRefreshView, AdminMeView,
    AdminUserListView, AdminUserCreateView, AdminUserUpdateView, AdminUserOffboardView,
    PermissionRequestCreateView, PermissionRequestListView,
    PermissionRequestActionView, PermissionGrantListView, PermissionGrantRevokeView,
)
from .views import (
    UserListView, InactiveUserListView, UserDetailView, UserEditView, UserBulkActionView, PhotoModerationListView, PhotoApproveView,
    PhotoRejectView, PhotoBulkActionView, FaceVerificationListView, FaceVerificationApproveView,
    FaceVerificationRejectView, FaceVerificationBulkActionView, SubscriptionListView, SubscriptionGrantView,
    BulkGrantPremiumView,
    SubscriptionDowngradeView, SubscriptionCancelView, BoostGrantView, PaymentListView, SupportChatListView,
    SupportChatDetailView,
    AdminCreateSupportChatView, AdminCreateUserView, PricingPlanListView, PricingPlanUpdateView,
    DailyServiceListView, DailyServiceCreateView, DailyServiceUpdateView, DailyServiceDeleteView,
    UserDailyServiceListView, BlogListView, BlogUpdateView, AlertListView, AlertMarkReadView,
    AdminChatListView, AdminChatDetailView, AdminChatReopenView,
    AnnouncementListCreateView, AnnouncementDetailView, AnnouncementMediaDeleteView,
    CommunityMemberListView, CommunityMemberDeactivateView, CommunityMemberReactivateView,
    CommunityReportListView, CommunityReportActionView,
    CommunityPostListView, CommunityCommentListView,
)

urlpatterns = [
    path('auth/login/', AdminLoginView.as_view(), name='admin-auth-login'),
    path('auth/refresh/', AdminRefreshView.as_view(), name='admin-auth-refresh'),
    path('auth/me/', AdminMeView.as_view(), name='admin-auth-me'),
    path('admin-users/', AdminUserListView.as_view(), name='admin-users-list'),
    path('admin-users/create/', AdminUserCreateView.as_view(), name='admin-users-create'),
    path('admin-users/<int:admin_id>/', AdminUserUpdateView.as_view(), name='admin-users-update'),
    path('admin-users/<int:admin_id>/offboard/', AdminUserOffboardView.as_view(), name='admin-users-offboard'),
    path('permissions/requests/', PermissionRequestListView.as_view(), name='permission-requests-list'),
    path('permissions/requests/create/', PermissionRequestCreateView.as_view(), name='permission-requests-create'),
    path('permissions/requests/action/', PermissionRequestActionView.as_view(), name='permission-requests-action'),
    path('permissions/grants/', PermissionGrantListView.as_view(), name='permission-grants-list'),
    path('permissions/grants/revoke/', PermissionGrantRevokeView.as_view(), name='permission-grants-revoke'),
    path('users/', UserListView.as_view(), name='admin-user-list'),
    path('users/inactive/', InactiveUserListView.as_view(), name='admin-user-inactive-list'),
    path('users/create/', AdminCreateUserView.as_view(), name='admin-user-create'),
    path('users/<int:user_id>/', UserDetailView.as_view(), name='admin-user-detail'),
    path('users/<int:user_id>/edit/', UserEditView.as_view(), name='admin-user-edit'),
    path('users/bulk-action/', UserBulkActionView.as_view(), name='admin-user-bulk-action'),
    path('photos/', PhotoModerationListView.as_view(), name='admin-photo-list'),
    path('photos/approve/', PhotoApproveView.as_view(), name='admin-photo-approve'),
    path('photos/reject/', PhotoRejectView.as_view(), name='admin-photo-reject'),
    path('photos/bulk-action/', PhotoBulkActionView.as_view(), name='admin-photo-bulk-action'),
    path('verifications/', FaceVerificationListView.as_view(), name='admin-verification-list'),
    path('verifications/approve/', FaceVerificationApproveView.as_view(), name='admin-verification-approve'),
    path('verifications/reject/', FaceVerificationRejectView.as_view(), name='admin-verification-reject'),
    path('verifications/bulk-action/', FaceVerificationBulkActionView.as_view(),
         name='admin-verification-bulk-action'),
    path('admin/subscriptions/', SubscriptionListView.as_view(), name='admin-subscription-list'),
    path('admin/subscriptions/grant/', SubscriptionGrantView.as_view(), name='admin-subscription-grant'),
    path('admin/subscriptions/grant-all/', BulkGrantPremiumView.as_view(), name='admin-subscription-grant-all'),
    path('admin/subscriptions/downgrade/', SubscriptionDowngradeView.as_view(), name='admin-subscription-downgrade'),
    path('admin/subscriptions/cancel/', SubscriptionCancelView.as_view(), name='admin-subscription-cancel'),
    path('admin/boost/grant/', BoostGrantView.as_view(), name='admin-boost-grant'),
    path('admin/payments/', PaymentListView.as_view(), name='admin-payment-list'),
    path('admin/pricing-plans/', PricingPlanListView.as_view(), name='admin-pricing-plan-list'),
    path('admin/pricing-plans/update/', PricingPlanUpdateView.as_view(), name='admin-pricing-plan-update'),
    path('admin/daily-services/', DailyServiceListView.as_view(), name='admin-daily-service-list'),
    path('admin/daily-services/create/', DailyServiceCreateView.as_view(), name='admin-daily-service-create'),
    path('admin/daily-services/update/', DailyServiceUpdateView.as_view(), name='admin-daily-service-update'),
    path('admin/daily-services/delete/', DailyServiceDeleteView.as_view(), name='admin-daily-service-delete'),
    path('admin/user-daily-services/', UserDailyServiceListView.as_view(), name='admin-user-daily-service-list'),
    path('support/', SupportChatListView.as_view(), name='admin-support-list'),
    path('support/<int:chat_id>/', SupportChatDetailView.as_view(), name='admin-support-detail'),
    path('support/create-chat/', AdminCreateSupportChatView.as_view(), name='admin-support-create-chat'),
    path('blogs/', BlogListView.as_view(), name='admin-blog-list'),
    path('blogs/<int:blog_id>/', BlogUpdateView.as_view(), name='admin-blog-detail'),
    path('alerts/', AlertListView.as_view(), name='admin-alert-list'),
    path('alerts/mark-read/', AlertMarkReadView.as_view(), name='admin-alert-mark-read'),
    path('chats/', AdminChatListView.as_view(), name='admin-chat-list'),
    path('chats/<int:room_id>/', AdminChatDetailView.as_view(), name='admin-chat-detail'),
    path('chats/<int:room_id>/reopen/', AdminChatReopenView.as_view(), name='admin-chat-reopen'),
    path('announcements/', AnnouncementListCreateView.as_view(), name='admin-announcement-list-create'),
    path('announcements/<int:announcement_id>/', AnnouncementDetailView.as_view(), name='admin-announcement-detail'),
    path('announcements/<int:announcement_id>/media/<int:media_id>/', AnnouncementMediaDeleteView.as_view(),
         name='admin-announcement-media-delete'),
    path('community/members/', CommunityMemberListView.as_view(),
         name='admin-community-member-list'),
    path('community/members/deactivate/', CommunityMemberDeactivateView.as_view(),
         name='admin-community-member-deactivate'),
    path('community/members/reactivate/', CommunityMemberReactivateView.as_view(),
         name='admin-community-member-reactivate'),
    path('community/reports/', CommunityReportListView.as_view(),
         name='admin-community-report-list'),
    path('community/reports/<int:report_id>/action/', CommunityReportActionView.as_view(),
         name='admin-community-report-action'),
    path('community/posts/', CommunityPostListView.as_view(),
         name='admin-community-post-list'),
    path('community/comments/', CommunityCommentListView.as_view(),
         name='admin-community-comment-list'),
]
