# Generated by Django 5.2.9 on 2026-07-02 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Profile Like'), ('match', 'Match'), ('post_like', 'Post Like'), ('comment', 'Comment'), ('comment_like', 'Comment Like')], db_index=True, max_length=20)),
                ('target_id', models.IntegerField(blank=True, help_text='Related object id (post / comment / match), for deep-linking', null=True)),
                ('preview_text', models.TextField(blank=True, help_text='Snapshot of comment text (comment / comment_like)', null=True)),
                ('image_url', models.TextField(blank=True, help_text='Snapshot of post thumbnail url (post_like / comment)', null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(help_text='User who triggered the notification', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_dde14f_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx')],
            },
        ),
    ]
