# Generated by Django 5.2.9 on 2026-07-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Profile Like'), ('match', 'Match'), ('post_like', 'Post Like'), ('comment', 'Comment'), ('comment_like', 'Comment Like'), ('chat_request_accepted', 'Chat Request Accepted'), ('guardian_request', 'Guardian Request')], db_index=True, max_length=30),
        ),
    ]
