# Generated by Django 5.2.7 on 2025-10-31 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('support', 'Support Staff')], default='moderator', max_length=20)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_moderate_photos', models.BooleanField(default=True)),
                ('can_manage_payments', models.BooleanField(default=False)),
                ('can_manage_subscriptions', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=True)),
                ('can_send_notifications', models.BooleanField(default=False)),
                ('can_manage_matches', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'db_table': 'admin_panel_adminuser',
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('user_view', 'View User'), ('user_edit', 'Edit User'), ('user_verify', 'Verify User'), ('user_suspend', 'Suspend User'), ('photo_approve', 'Approve Photo'), ('photo_reject', 'Reject Photo'), ('payment_view', 'View Payment'), ('subscription_grant', 'Grant Subscription'), ('notification_send', 'Send Notification'), ('match_view', 'View Match'), ('export_data', 'Export Data'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('target_user_id', models.IntegerField(blank=True, help_text='ID of user affected by action', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='admin_panel.adminuser')),
            ],
            options={
                'db_table': 'admin_panel_activitylog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', '-created_at'], name='admin_panel_admin_u_b3415e_idx'), models.Index(fields=['action', '-created_at'], name='admin_panel_action_99e27f_idx')],
            },
        ),
    ]
