# Generated by Django 5.2.7 on 2025-11-18 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSupportChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('message_count', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_message_preview', models.TextField(blank=True, max_length=200)),
                ('unread_by_admin', models.IntegerField(default=0)),
                ('unread_by_user', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_chats', to='admin_panel.adminuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_panel_supportchat',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminSupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], db_index=True, max_length=10)),
                ('message', models.TextField(max_length=5000)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages_sent', to='admin_panel.adminuser')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='admin_panel.adminsupportchat')),
                ('user_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_panel_supportmessage',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adminsupportchat',
            index=models.Index(fields=['user', '-created_at'], name='admin_panel_user_id_d10d51_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsupportchat',
            index=models.Index(fields=['admin_user', '-created_at'], name='admin_panel_admin_u_1d7484_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsupportchat',
            index=models.Index(fields=['status', '-last_message_at'], name='admin_panel_status_a10f84_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsupportmessage',
            index=models.Index(fields=['chat', '-created_at'], name='admin_panel_chat_id_3dac90_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsupportmessage',
            index=models.Index(fields=['chat', 'is_read'], name='admin_panel_chat_id_70a1f2_idx'),
        ),
    ]
