# Generated by Django 5.2.9 on 2026-04-07 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_broadcastmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='message',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.CreateModel(
            name='BroadcastMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='broadcast_media/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='admin_panel.broadcastmessage')),
            ],
            options={
                'db_table': 'admin_panel_broadcastmedia',
                'ordering': ['order'],
            },
        ),
    ]
