# Generated by Django 5.2.9 on 2026-04-07 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_add_broadcast_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsupportmessage',
            name='broadcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to='admin_panel.broadcastmessage'),
        ),
        migrations.AlterField(
            model_name='adminsupportmessage',
            name='message',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
