# Generated by Django 5.2.9 on 2026-04-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_add_broadcast_to_support_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='filter_age_group',
            field=models.CharField(default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='filter_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('all', 'All')], default='all', max_length=5),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='filter_platform',
            field=models.CharField(choices=[('tg_app', 'Telegram Mini App'), ('mobile', 'Mobile App'), ('all', 'All')], default='all', max_length=10),
        ),
    ]
