# Generated by Django 5.2.9 on 2026-05-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_rebuild_admin_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminuser',
            new_name='admin_users_email_91b518_idx',
            old_name='admin_users_email_b7e5f0_idx',
        ),
        migrations.RenameIndex(
            model_name='adminuser',
            new_name='admin_users_role_6dd4c7_idx',
            old_name='admin_users_role_e8c2a1_idx',
        ),
        migrations.RenameIndex(
            model_name='permissiongrant',
            new_name='admin_permi_granted_668d31_idx',
            old_name='admin_permi_granted_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='permissiongrant',
            new_name='admin_permi_permiss_1f58d6_idx',
            old_name='admin_permi_permiss_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='permissionrequest',
            new_name='admin_permi_status_54e426_idx',
            old_name='admin_permi_status_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='permissionrequest',
            new_name='admin_permi_request_9cbc3c_idx',
            old_name='admin_permi_request_j0k1l2_idx',
        ),
    ]
