# Generated by Django 5.2.9 on 2026-05-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_rename_admin_users_email_b7e5f0_idx_admin_users_email_91b518_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsupportmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminsupportmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminsupportmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
