# Generated by Django 5.2.9 on 2026-05-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_add_message_edit_delete_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('slug', models.CharField(db_index=True, max_length=280, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_panel_blogs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='admin_panel_created_b09168_idx'), models.Index(fields=['slug'], name='admin_panel_slug_a2528b_idx')],
            },
        ),
    ]
