# Generated by Django 5.2.9 on 2026-05-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_add_blog_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blog',
            new_name='blogs_created_3c1aa8_idx',
            old_name='admin_panel_created_b09168_idx',
        ),
        migrations.RenameIndex(
            model_name='blog',
            new_name='blogs_slug_ec41d2_idx',
            old_name='admin_panel_slug_a2528b_idx',
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blogs',
        ),
    ]
