# Generated by Django 5.2.9 on 2026-05-24 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_rename_blog_table'),
        ('reports', '0005_seed_report_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('report_created', 'Report Created'), ('user_flagged', 'User Flagged'), ('verification_failed', 'Verification Failed')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=10)),
                ('message', models.TextField(max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_alerts', to='admin_panel.adminuser')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='reports.report')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_panel_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='admin_panel_is_read_7c9ba6_idx'), models.Index(fields=['alert_type', '-created_at'], name='admin_panel_alert_t_6b3edd_idx'), models.Index(fields=['severity', '-created_at'], name='admin_panel_severit_c1c124_idx')],
            },
        ),
    ]
