# Generated by Django 5.2.9 on 2026-07-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_announcement_announcementmedia_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='announcement',
            name='announcemen_is_publ_55a606_idx',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='is_published',
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(db_index=True, default='published', max_length=50),
        ),
        migrations.AddField(
            model_name='announcement',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', '-created_at'], name='announcemen_status_3a8820_idx'),
        ),
    ]
