# Generated by Django 5.2.9 on 2026-07-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_remove_announcement_announcemen_is_publ_55a606_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('security', 'Security'), ('tech', 'Tech'), ('live', 'Live'), ('event', 'Event'), ('opportunity', 'Opportunity'), ('survey', 'Survey'), ('success', 'Success'), ('reminder', 'Reminder'), ('community', 'Community'), ('uzuk', 'Uzuk'), ('tip', 'Tip'), ('agent', 'Agent')], db_index=True, default='agent', max_length=20),
        ),
    ]
