# Generated by Django 5.2.9 on 2026-07-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_announcement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastmessage',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='adminsupportmessage',
            name='broadcast',
        ),
        migrations.DeleteModel(
            name='BroadcastMedia',
        ),
        migrations.DeleteModel(
            name='BroadcastMessage',
        ),
    ]
