# Generated by Django 5.2.9 on 2026-02-02 08:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deleteduserstats',
            options={'ordering': ['-deleted_at'], 'verbose_name': 'Deleted User Statistic', 'verbose_name_plural': 'Deleted User Statistics'},
        ),
        migrations.AddField(
            model_name='deleteduserstats',
            name='days_active',
            field=models.IntegerField(default=0, help_text='Number of days user was active on platform'),
        ),
        migrations.AddField(
            model_name='deleteduserstats',
            name='deletion_reason',
            field=models.CharField(blank=True, choices=[('found_match', 'Found Match'), ('not_satisfied', 'Not Satisfied with Service'), ('privacy_concerns', 'Privacy Concerns'), ('too_expensive', 'Too Expensive'), ('no_matches', 'No Matches'), ('harassment', 'Harassment'), ('technical_issues', 'Technical Issues'), ('other', 'Other'), ('not_specified', 'Not Specified')], db_index=True, default='not_specified', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deleteduserstats',
            name='had_matches',
            field=models.BooleanField(default=False, help_text='Whether user had any matches'),
        ),
        migrations.AddField(
            model_name='deleteduserstats',
            name='subscription_type',
            field=models.CharField(default='free', help_text='Subscription level at deletion: free, premium, pro', max_length=20),
        ),
        migrations.AddField(
            model_name='deleteduserstats',
            name='total_likes_received',
            field=models.IntegerField(default=0, help_text='Total likes received by user'),
        ),
        migrations.AddField(
            model_name='deleteduserstats',
            name='total_likes_sent',
            field=models.IntegerField(default=0, help_text='Total likes sent by user'),
        ),
        migrations.AddField(
            model_name='deleteduserstats',
            name='total_matches',
            field=models.IntegerField(default=0, help_text='Total number of matches'),
        ),
        migrations.AddField(
            model_name='deleteduserstats',
            name='total_messages_sent',
            field=models.IntegerField(default=0, help_text='Total messages sent'),
        ),
        migrations.AlterField(
            model_name='deleteduserstats',
            name='age',
            field=models.IntegerField(help_text='Age at time of deletion', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='deleteduserstats',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deleteduserstats',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deleteduserstats',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1),
        ),
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(db_index=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('ios', 'iOS'), ('android', 'Android')], default='web', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_engagements',
                'ordering': ['-session_start'],
                'indexes': [models.Index(fields=['session_start'], name='user_engage_session_c3044d_idx'), models.Index(fields=['user', 'session_start'], name='user_engage_user_id_9116b9_idx')],
            },
        ),
    ]
