# Generated by Django 5.2.9 on 2026-03-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_userengagement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduserstats',
            name='deletion_note',
            field=models.TextField(blank=True, help_text="Additional comments from user about why they're leaving", null=True),
        ),
    ]
