# Generated by Django 5.2.9 on 2026-03-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_deleteduserstats_deletion_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteduserstats',
            name='deletion_reason',
            field=models.CharField(blank=True, choices=[('found_match', 'Found Match'), ('not_satisfied', 'Not Satisfied with Service'), ('privacy_concerns', 'Privacy Concerns'), ('too_expensive', 'Too Expensive'), ('no_matches', 'No Matches'), ('harassment', 'Harassment'), ('technical_issues', 'Technical Issues'), ('not_specified', 'Not Specified'), ('other', 'Other')], db_index=True, default='not_specified', max_length=50, null=True),
        ),
    ]
