# Generated by Django 5.2.9 on 2026-03-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_deleteduserstats_deletion_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduserstats',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
