# Generated by Django 5.2.9 on 2026-04-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_deleteduserstats_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduserstats',
            name='platform',
            field=models.CharField(blank=True, db_index=True, help_text='Platform user was on: tg_app or mobile', max_length=20, null=True),
        ),
    ]
