# Generated by Django 5.2.9 on 2026-04-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_deleteduserstats_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteduserstats',
            name='country',
            field=models.CharField(db_index=True, default='Uzbekistan', max_length=100),
        ),
        migrations.AlterField(
            model_name='deleteduserstats',
            name='deletion_reason',
            field=models.CharField(choices=[('found_match', 'Found Match'), ('not_satisfied', 'Not Satisfied with Service'), ('privacy_concerns', 'Privacy Concerns'), ('too_expensive', 'Too Expensive'), ('no_matches', 'No Matches'), ('harassment', 'Harassment'), ('technical_issues', 'Technical Issues'), ('not_specified', 'Not Specified'), ('other', 'Other')], db_index=True, default='not_specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='deleteduserstats',
            name='platform',
            field=models.CharField(db_index=True, default='tg_app', help_text='Platform user was on: tg_app or mobile', max_length=20),
        ),
    ]
