# Generated by Django 5.2.9 on 2026-05-23 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_alter_userengagement_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userengagement',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='events',
            field=models.JSONField(blank=True, default=list, help_text='List of user events: [{type, page, timestamp, metadata}]'),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='matches_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='messages_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='page_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique session identifier from frontend', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userengagement',
            name='platform',
            field=models.CharField(choices=[('web', 'Web'), ('ios', 'iOS'), ('android', 'Android'), ('tg_web', 'Telegram Web App')], default='tg_web', max_length=20),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['session_id'], name='user_engage_session_5f2221_idx'),
        ),
    ]
