# Generated by Django 5.2.9 on 2026-05-23 05:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_userengagement_dislikes_count_userengagement_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userengagement',
            name='session_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=64, unique=True),
        ),
    ]
