# Generated by Django 5.2.9 on 2026-05-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_alter_userengagement_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userengagement',
            name='dislikes_count',
        ),
        migrations.RemoveField(
            model_name='userengagement',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='userengagement',
            name='matches_count',
        ),
        migrations.RemoveField(
            model_name='userengagement',
            name='messages_sent',
        ),
        migrations.RemoveField(
            model_name='userengagement',
            name='page_views',
        ),
        migrations.AlterField(
            model_name='userengagement',
            name='events',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
