# Generated by Django 5.2.9 on 2026-07-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_remove_engagement_counters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleteduserstats',
            name='country',
        ),
    ]
