# Generated by Django 5.2.9 on 2026-04-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='initiation_type',
            field=models.CharField(choices=[('female_initiated', 'Female Initiated'), ('male_initiated_after_like', 'Male Initiated After Like'), ('male_initiated_premium', 'Male Initiated (Premium)'), ('male_initiated_super_message', 'Male Initiated (Super Message)')], db_index=True, max_length=30),
        ),
    ]
