# Generated by Django 5.2.9 on 2026-05-11 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatroom_initiation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('missed_call', 'Missed Call'), ('call', 'Call')], db_index=True, default='text', max_length=15),
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('answered', 'Answered'), ('ended', 'Ended'), ('missed', 'Missed'), ('rejected', 'Rejected'), ('busy', 'Busy')], db_index=True, default='ringing', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('timeout', 'Timeout')], max_length=15, null=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='chat.chatroom')),
            ],
            options={
                'db_table': 'chat_call',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='call',
            field=models.ForeignKey(blank=True, help_text='Related call for missed_call/call message types', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.call'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['room', '-started_at'], name='chat_call_room_id_4d4bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['caller', '-started_at'], name='chat_call_caller__3cc38c_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['receiver', '-started_at'], name='chat_call_receive_583082_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['status'], name='chat_call_status_433baa_idx'),
        ),
    ]
