# Generated by Django 5.2.9 on 2026-06-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_add_call_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='last_message_preview',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='message_count',
        ),
        migrations.DeleteModel(
            name='TypingStatus',
        ),
    ]
