# Generated by Django 5.2.9 on 2026-06-01 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chatroom_last_message_preview_and_more'),
        ('matching', '0014_remove_profileboost_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='initial_message',
            field=models.TextField(blank=True, help_text='First message sent with chat request', null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_seen',
            field=models.BooleanField(default=False, help_text='Whether the recipient has seen the chat request'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], db_index=True, default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='initiation_type',
            field=models.CharField(choices=[('female_initiated', 'Female Initiated'), ('male_initiated_after_like', 'Male Initiated After Like'), ('male_initiated_premium', 'Male Initiated (Premium)'), ('male_initiated_super_message', 'Male Initiated (Super Message)'), ('male_initiated_request', 'Male Initiated (Request)')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['status'], name='chat_chatro_status_367f28_idx'),
        ),
    ]
