# Generated by Django 5.2.9 on 2026-06-06 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_add_system_message_type'),
        ('matching', '0014_remove_profileboost_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user1', 'user2'), name='unique_pending_chat_request'),
        ),
    ]
