# Generated by Django 5.2.9 on 2026-06-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_add_unique_pending_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='active', max_length=10),
        ),
    ]
