# Generated by Django 5.2.9 on 2026-06-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_add_match_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
    ]
