# Generated by Django 5.2.9 on 2026-06-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_add_message_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('no_match_after_popups', 'No match after 3 popups'), ('expired_inactive', 'Expired due to inactivity'), ('user_blocked', 'User blocked'), ('manual', 'Manually deactivated')], max_length=30, null=True),
        ),
    ]
