# Generated by Django 5.2.9 on 2026-08-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_add_deactivation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='initiation_type',
            field=models.CharField(choices=[('female_initiated', 'Female Initiated'), ('female_initiated_after_like', 'Female Initiated After Like'), ('female_initiated_premium', 'Female Initiated (Premium)'), ('female_initiated_super_message', 'Female Initiated (Super Message)'), ('female_initiated_request', 'Female Initiated (Request)'), ('male_initiated_after_like', 'Male Initiated After Like'), ('male_initiated_premium', 'Male Initiated (Premium)'), ('male_initiated_super_message', 'Male Initiated (Super Message)'), ('male_initiated_request', 'Male Initiated (Request)'), ('mutual_like', 'Mutual Like'), ('premium', 'Premium'), ('super_message', 'Super Message'), ('request', 'Request')], db_index=True, max_length=30),
        ),
    ]
