# Generated by Django 5.2.9 on 2026-06-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_announcement_announcementmedia_and_more'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityprofile',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_community_profiles', to='admin_panel.adminuser'),
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='deactivated_by_admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='deactivation_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('verification_removed', 'Verification Removed'), ('spam', 'Spam'), ('abuse', 'Abuse or Harassment'), ('fake_profile', 'Fake Profile'), ('inappropriate_content', 'Inappropriate Content'), ('tos_violation', 'Terms of Service Violation'), ('other', 'Other')], max_length=32, null=True),
        ),
    ]
