# Generated by Django 5.2.9 on 2026-03-03 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('profile', 'Profile'), ('message', 'Message')], max_length=10)),
                ('reason', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Under Investigation'), ('resolved', 'Action Taken'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='chat.message')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_user', 'status'], name='chat_report_target__770991_idx'), models.Index(fields=['created_at'], name='chat_report_created_d9d75f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('report_type', 'profile')), fields=('reporter', 'target_user'), name='unique_profile_report'), models.UniqueConstraint(condition=models.Q(('report_type', 'message')), fields=('reporter', 'message'), name='unique_message_report')],
            },
        ),
    ]
