# Generated by Django 5.2.9 on 2026-03-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
