# Generated by Django 5.2.9 on 2026-05-23 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_add_message_edit_delete_fields'),
        ('reports', '0003_alter_report_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolution_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to='admin_panel.adminuser'),
        ),
        migrations.CreateModel(
            name='ReportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Report Created'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added'), ('assigned', 'Assigned')], db_index=True, max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_events', to='admin_panel.adminuser')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reports.report')),
            ],
            options={
                'db_table': 'report_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['report', 'created_at'], name='report_even_report__11c885_idx')],
            },
        ),
    ]
