# Generated by Django 5.2.9 on 2026-05-23 06:42

from django.db import migrations


def seed_created_events(apps, schema_editor):
    """Create 'created' event for all existing reports."""
    Report = apps.get_model('reports', 'Report')
    ReportEvent = apps.get_model('reports', 'ReportEvent')

    events_to_create = []
    for report in Report.objects.all():
        events_to_create.append(
            ReportEvent(
                report=report,
                event_type='created',
                actor=None,
                from_status=None,
                to_status='pending',
                note=None,
                metadata={},
                created_at=report.created_at
            )
        )

    if events_to_create:
        ReportEvent.objects.bulk_create(events_to_create)


def reverse_seed(apps, schema_editor):
    """Remove all 'created' events."""
    ReportEvent = apps.get_model('reports', 'ReportEvent')
    ReportEvent.objects.filter(event_type='created').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_resolution_note_report_resolved_at_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_created_events, reverse_seed),
    ]
