# Generated by Django 5.2.7 on 2025-10-23 14:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('religious_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('lifestyle_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('demographic_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('distance_km', models.FloatField(blank=True, db_index=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('potential_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_compatibility_scores', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_compatibilityscore',
                'indexes': [models.Index(fields=['user', '-overall_score'], name='matching_co_user_id_0cf9c0_idx'), models.Index(fields=['user', 'distance_km'], name='matching_co_user_id_c7f3d2_idx')],
                'unique_together': {('user', 'potential_match')},
            },
        ),
        migrations.CreateModel(
            name='DailyLikeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('super_likes_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_dailylikelimit',
                'indexes': [models.Index(fields=['user', 'date'], name='matching_da_user_id_005d2e_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_type', models.CharField(choices=[('regular', 'Regular Like'), ('super', 'Super Like')], db_index=True, default='regular', max_length=10)),
                ('is_seen', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_like',
                'indexes': [models.Index(fields=['target', 'is_seen'], name='matching_li_target__211f23_idx'), models.Index(fields=['-created_at'], name='matching_li_created_689c07_idx')],
                'unique_together': {('user', 'target')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('matched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unmatched_at', models.DateTimeField(blank=True, null=True)),
                ('unmatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_relationships', to=settings.AUTH_USER_MODEL)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_match',
                'indexes': [models.Index(fields=['user1', 'is_active'], name='matching_ma_user1_i_86296c_idx'), models.Index(fields=['user2', 'is_active'], name='matching_ma_user2_i_700385_idx'), models.Index(fields=['-matched_at'], name='matching_ma_matched_a25d37_idx'), models.Index(fields=['-last_message_at'], name='matching_ma_last_me_44c6b6_idx')],
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swipes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_swipe',
                'indexes': [models.Index(fields=['user', 'action'], name='matching_sw_user_id_b603ee_idx'), models.Index(fields=['target', 'action'], name='matching_sw_target__453a23_idx'), models.Index(fields=['-created_at'], name='matching_sw_created_f4f560_idx')],
                'unique_together': {('user', 'target')},
            },
        ),
    ]
