# Generated by Django 5.2.7 on 2025-10-27 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('boost_multiplier', models.IntegerField(default=10, help_text='Visibility multiplier')),
                ('views_gained', models.IntegerField(default=0)),
                ('likes_gained', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_profileboost',
                'ordering': ['-activated_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='matching_pr_user_id_5f1714_idx'), models.Index(fields=['expires_at'], name='matching_pr_expires_02f7c8_idx')],
            },
        ),
    ]
