# Generated by Django 5.2.7 on 2025-11-28 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_profileboost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compatibilityscore',
            name='religious_score',
        ),
        migrations.AddField(
            model_name='compatibilityscore',
            name='psychological_score',
            field=models.IntegerField(default=50, help_text='Psychological compatibility (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='compatibilityscore',
            name='demographic_score',
            field=models.IntegerField(help_text='Demographic compatibility (-70 to 100)', validators=[django.core.validators.MinValueValidator(-70), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='compatibilityscore',
            name='lifestyle_score',
            field=models.IntegerField(help_text='Lifestyle compatibility (-30 to 100)', validators=[django.core.validators.MinValueValidator(-30), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='compatibilityscore',
            name='overall_score',
            field=models.IntegerField(db_index=True, help_text='Overall compatibility (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
