# Generated by Django 5.2.9 on 2026-02-26 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_remove_compatibilityscore_religious_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compatibilityscore',
            name='psychological_score',
            field=models.IntegerField(default=0, help_text='Psychological compatibility (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
