# Generated by Django 5.2.9 on 2026-02-27 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_alter_compatibilityscore_psychological_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_viewers', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_profileview',
                'indexes': [models.Index(fields=['target', '-created_at'], name='matching_pr_target__4b4ce3_idx')],
                'unique_together': {('viewer', 'target')},
            },
        ),
    ]
