# Generated by Django 5.2.9 on 2026-02-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_add_profileview_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profileview',
            name='matching_pr_target__4b4ce3_idx',
        ),
    ]
