# Generated by Django 5.2.9 on 2026-04-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_photoreveal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylikelimit',
            name='skips_count',
            field=models.IntegerField(default=0),
        ),
    ]
