# Generated by Django 5.2.9 on 2026-04-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_dailylikelimit_skips_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileview',
            name='shown_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
