# Generated by Django 5.2.9 on 2026-05-14 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_add_shown_date_to_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipe',
            name='view_duration',
            field=models.PositiveSmallIntegerField(default=0, help_text='Profile view duration in seconds (max 120)', validators=[django.core.validators.MaxValueValidator(120)]),
        ),
    ]
