# Generated by Django 5.2.9 on 2026-05-14 05:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0010_add_view_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='Compatibility score 0-100', validators=[django.core.validators.MaxValueValidator(100)])),
                ('reasons', models.JSONField(default=list, help_text='Match reasons list')),
                ('explanation', models.CharField(blank=True, help_text='AI explanation', max_length=500, null=True)),
                ('common_values', models.JSONField(default=list, help_text='Common values list')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shown', 'Shown'), ('liked', 'Liked'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('batch_date', models.DateField(db_index=True, help_text='Recommendation date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_ai_recommendation',
                'indexes': [models.Index(fields=['user', 'batch_date', 'status'], name='matching_ai_user_id_baf0ad_idx'), models.Index(fields=['user', '-score'], name='matching_ai_user_id_0e0077_idx')],
                'unique_together': {('user', 'candidate', 'batch_date')},
            },
        ),
    ]
