# Generated by Django 5.2.9 on 2026-05-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0011_add_ai_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='is_second_chance',
            field=models.BooleanField(default=False, help_text='User previously swiped this candidate'),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='explanation',
            field=models.TextField(blank=True, help_text='AI generated explanation in Uzbek', null=True),
        ),
    ]
