# Generated by Django 5.2.9 on 2026-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0012_change_explanation_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airecommendation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shown', 'Shown'), ('liked', 'Liked'), ('skipped', 'Skipped'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
    ]
