# Generated by Django 5.2.9 on 2026-06-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0013_alter_airecommendation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileboost',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='matching_ma_last_me_44c6b6_idx',
        ),
        migrations.RemoveField(
            model_name='dailylikelimit',
            name='super_likes_count',
        ),
        migrations.RemoveField(
            model_name='match',
            name='last_message_at',
        ),
        migrations.RemoveField(
            model_name='match',
            name='unmatched_at',
        ),
        migrations.RemoveField(
            model_name='match',
            name='unmatched_by',
        ),
        migrations.DeleteModel(
            name='ProfileBoost',
        ),
    ]
