# Generated by Django 5.2.9 on 2026-06-13 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_add_match_confirmation'),
        ('matching', '0014_remove_profileboost_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup_count', models.IntegerField(default=0)),
                ('user1_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user1_responded_at', models.DateTimeField(blank=True, null=True)),
                ('user2_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user2_responded_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_confirmation', to='chat.chatroom')),
            ],
            options={
                'db_table': 'matching_match_confirmation',
            },
        ),
    ]
