# Generated by Django 5.2.9 on 2026-06-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0015_add_match_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchconfirmation',
            name='response_history',
            field=models.JSONField(default=list),
        ),
    ]
