# Generated by Django 5.2.9 on 2026-06-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0016_add_response_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchconfirmation',
            name='user1_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('postponed', 'Postponed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='matchconfirmation',
            name='user2_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('postponed', 'Postponed')], default='pending', max_length=10),
        ),
    ]
