# Generated by Django 5.2.9 on 2026-06-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0017_alter_matchconfirmation_user1_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoReveal',
        ),
    ]
