# Generated by Django 5.2.9 on 2026-07-01 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0018_delete_photoreveal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoReveal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('revealed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_revealed_by', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_reveals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_photoreveal',
                'indexes': [models.Index(fields=['viewer', '-created_at'], name='matching_ph_viewer__240a6d_idx')],
                'unique_together': {('viewer', 'revealed_user')},
            },
        ),
    ]
