# Generated by Django 5.2.9 on 2026-07-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0019_photoreveal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoReveal',
        ),
    ]
