# Generated by Django 5.2.9 on 2026-02-11 17:55

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QAEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('question_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_embeddings',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['question_embedding'], m=16, name='qa_embedding_hnsw_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_question', models.TextField()),
                ('canonical_embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('total_count', models.IntegerField(default=1)),
                ('male_count', models.IntegerField(default=0)),
                ('female_count', models.IntegerField(default=0)),
                ('age_18_25', models.IntegerField(default=0)),
                ('age_26_35', models.IntegerField(default=0)),
                ('age_36_45', models.IntegerField(default=0)),
                ('age_46_plus', models.IntegerField(default=0)),
                ('first_asked', models.DateTimeField(auto_now_add=True)),
                ('last_asked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question_analytics',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['canonical_embedding'], m=16, name='qa_canonical_hnsw_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
