# Generated by Django 5.2.9 on 2026-04-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_useraiconversation_useraimessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraiconversation',
            name='thread_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
