# Generated by Django 5.2.9 on 2026-07-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_useraiconversation_thread_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminaimessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='adminaimemory',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='AdminAIConversation',
        ),
        migrations.DeleteModel(
            name='AdminAIMessage',
        ),
        migrations.DeleteModel(
            name='AdminAIMemory',
        ),
    ]
