from django.urls import path

from .views import (
    FilterOptionsView,
    ActiveUsersStatsView,
    NewUsersStatsView,
    DeletedUsersStatsView,
    EngagementStatsView,
    SupportStatsView,
    MatchingStatsView,
    ChatStatsView,
    AdminLoginView,
    AdminTokenRefreshView,
    LandingPageStats,
    LandingPageContact,
    TopUsersView,
    DeletedUsersListView,
    PendingDeletionUsersListView,
    ParentConnectionListView,
    UserEngagementView,
    MatchesListView,
    MatchesStatsView,
    MediaMatchCountView,
    MediaMatchCountResultView,
)
from .match_types_views import (
    MatchOriginView,
    MissedPopupsView,
)
from .behavior_views import (
    BehaviorSummaryView,
    BehaviorFunnelView,
    BehaviorPagesView,
    BehaviorLiveSnapshotView,
    BehaviorUsersListView,
    BehaviorUserDetailView,
    BehaviorTrackView,
    BehaviorTrackBatchView,
    BehaviorFeatureUsageView,
    ValueTrendsView,
)

app_name = 'stats'

urlpatterns = [
    path('auth/login/', AdminLoginView.as_view(), name='admin-login'),
    path('auth/token/refresh/', AdminTokenRefreshView.as_view(), name='admin-token-refresh'),
    path('filters/options/', FilterOptionsView.as_view(), name='filter-options'),
    path('users/active/', ActiveUsersStatsView.as_view(), name='active-users'),
    path('users/new/', NewUsersStatsView.as_view(), name='new-users'),
    path('users/deleted/', DeletedUsersStatsView.as_view(), name='deleted-users'),
    path('users/deleted/list/', DeletedUsersListView.as_view(), name='deleted-users-list'),
    path('users/pending-deletion/', PendingDeletionUsersListView.as_view(), name='pending-deletion-users'),
    path('users/top/', TopUsersView.as_view(), name='top-users'),
    path('engagement/', EngagementStatsView.as_view(), name='engagement'),
    path('support/', SupportStatsView.as_view(), name='support'),
    path('matching/', MatchingStatsView.as_view(), name='matching'),
    path('chats/', ChatStatsView.as_view(), name='chats'),
    path("landing-page/", LandingPageStats.as_view(), name="landing-page"),
    path("landing-page-contact/", LandingPageContact.as_view(), name="landing-page-contact"),
    path("parent-connections/", ParentConnectionListView.as_view(), name="parent-connections"),
    path("user-engagement/", UserEngagementView.as_view(), name="user-engagement"),
    path("matches/list/", MatchesListView.as_view(), name="matches-list"),
    path("matches/stats/", MatchesStatsView.as_view(), name="matches-stats"),
    path("matches/origin/", MatchOriginView.as_view(), name="matches-origin"),
    path("matches/missed-popups/", MissedPopupsView.as_view(), name="matches-missed-popups"),
    path("media/match-count/", MediaMatchCountView.as_view(), name="media-match-count"),
    path("media/match-count/result/<str:task_id>/", MediaMatchCountResultView.as_view(), name="media-match-count-result"),
    path("behavior/admin/summary/", BehaviorSummaryView.as_view(), name="behavior-summary"),
    path("behavior/admin/funnel/", BehaviorFunnelView.as_view(), name="behavior-funnel"),
    path("behavior/admin/pages/", BehaviorPagesView.as_view(), name="behavior-pages"),
    path("behavior/admin/live/snapshot/", BehaviorLiveSnapshotView.as_view(), name="behavior-live-snapshot"),
    path("behavior/admin/users/", BehaviorUsersListView.as_view(), name="behavior-users-list"),
    path("behavior/admin/users/<int:user_id>/", BehaviorUserDetailView.as_view(), name="behavior-user-detail"),
    path("behavior/admin/feature-usage/", BehaviorFeatureUsageView.as_view(), name="behavior-feature-usage"),
    path("value-trends/", ValueTrendsView.as_view(), name="value-trends"),
    path("behavior/track/", BehaviorTrackView.as_view(), name="behavior-track"),
    path("behavior/track/batch/", BehaviorTrackBatchView.as_view(), name="behavior-track-batch"),
]
