# Generated by Django 5.2.9 on 2026-07-28 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_relation', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed'), ('liked', 'Liked'), ('requested', 'Requested'), ('chatting', 'Chatting'), ('passed', 'Passed')], db_index=True, default='sent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_to_guardians', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_candidates', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guardian_forwarded_candidate',
                'indexes': [models.Index(fields=['child', '-created_at'], name='guardian_fo_child_i_cf10b3_idx'), models.Index(fields=['guardian', 'child'], name='guardian_fo_guardia_22359c_idx')],
                'unique_together': {('guardian', 'child', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='GuardianSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by_guardians', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_for_child', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guardian_seen',
                'indexes': [models.Index(fields=['guardian', 'child'], name='guardian_se_guardia_890e34_idx')],
                'unique_together': {('guardian', 'child', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('sister', 'Sister'), ('brother', 'Brother'), ('other', 'Other')], max_length=20)),
                ('child_approved', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships_as_child', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships_as_guardian', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guardian_guardianship',
                'indexes': [models.Index(fields=['guardian', 'is_active'], name='guardian_gu_guardia_77cb12_idx'), models.Index(fields=['child', 'child_approved'], name='guardian_gu_child_i_220148_idx')],
                'unique_together': {('guardian', 'child')},
            },
        ),
        migrations.CreateModel(
            name='SavedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_guardians', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_for_child', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guardian_saved_candidate',
                'indexes': [models.Index(fields=['guardian', 'child', '-created_at'], name='guardian_sa_guardia_51b668_idx')],
                'unique_together': {('guardian', 'child', 'candidate')},
            },
        ),
    ]
