# Generated by Django 5.2.9 on 2026-07-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardedcandidate',
            name='guardian_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='forwardedcandidate',
            name='guardian_relation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='forwardedcandidate',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guardianship',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
